config/routes.rb
NewSpoofer::Application.routes.draw do
root :to=>'mails#new'
get "/" => 'mails#new'
post "/" => 'mails#new'
match "/" =>'mails#new'
resources :mails
resources :contacts

end

app/models/mail.rb
class Mail < ActiveRecord::Base
attr_accessible :from, :to, :from_name, :subject, :message
set_primary_key "id"
validates :from, :to,:presence=>true,:format=>{:with=>/^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$/,:message=>" : Enter valid email address"}
validates :subject,:message,:from_name,:presence=>true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end

end

app/controllers/mailer_controller.rb
class MailerController < ApplicationController
require 'net/smtp' 
   def initialize(args)
      @from = args[:from]
      @from_name = args[:from_name] || ""
      @to = args[:to] 
      @subject = args[:subject] || ""
      @message = args[:message] || ""
  end
   def construct_message
      msg = "To: #{@to}\n"
      msg += "Subject: #{@subject}\n"
      msg += %Q(From: "#{@from_name}" <#{@from}>\n)
      #msg+= "From: #{@from}\n"
      msg+= "Reply-To: #{@from}\n"
      msg += "Date: #{Time.now}\n"
      msg += "Content-Type: text/plain; charset=utf-8\n\n"
      msg += @message
      msg
   end

   def sendmail
      smtp_server = 'smtp.elasticemail.com'
      smtp_port = 2525
      smtp = Net::SMTP.new smtp_server,smtp_port
      domain = "xyz@xyz.com"
      user = "ego.alternate@gmail.com"
      password = "e8b741aa-45ff-4cda-9060-d623153d2610"
      begin
        smtp.start(domain,user,password,:login) do
          smtp.send_message(construct_message,@from,@to)
        end
      rescue
        print "error occured"
      end
    end
end

app/controllers/mails_controller.rb
class MailsController < ApplicationController
  def index
     @mails = Mail.all
  end

  def show
	@mail = Mail.find(params[:id])
  end

  def new
	@mail  = Mail.new
  end

  def create
	@mail = Mail.new(params[:mail])
	if @mail.save
		m = MailerController.new(:from=>@mail.from,:to=>@mail.to,:from_name=>@mail.from_name,:message=>@mail.message,:subject=>@mail.subject)
		m.sendmail
		redirect_to mails_path, :notice=>"your mail successfully sent"
	else 

		render "new"
	end
  end



  def destroy
	@mail = Mail.find(params[:id])
	@mail.destroy
	redirect_to mails_path, :notice=>"Mail deleted"

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/mailer_helper.rb
module MailerHelper
end

app/helpers/mails_helper.rb
module MailsHelper
end

app/views/contacts/index.html.erb
<h2> Contact </h2>
<br/>
<label><b>Name : </b>Ameen Mohammed </label><br/>
<label><b>Google plus link : </b><a href="https://plus.google.com/114973484747547259214"> Google plus</a></label><br/>
<label> <b>Email: </b> 4IVI33n@gmail.com </label>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Email Spoofer</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Email Spoofer</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Compose mail", new_mail_path %></li>
	    <li><%= link_to "View mails", mails_path%></li>
            <li><%= link_to "Contact Me",contacts_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">

    <div class="row">
      <div class="span9">
	<% flash.each do |key,value| %>
		<p> <%=value%> </p>
		<%end%>
	<%= yield %>
	</div>
      <div class="span3">
        <h2>About Me</h2>
		Created By Ameen - 4IVI33n
      </div>
    </div>
  </div>
</body>
</html>